### ISSUE TITLE
select_STR_reads error

### ISSUE THREAD

**Issue by michaeldonaldson** [aakrosh/BaitSTR#6]
Hi, 

I installed BaitSTR by cloning the repository from Github, as suggested. After "make", I ran into an issue where I had to rename the .so files in the src folder (fastq.cpython-35m-x86_64-linux-gnu.so to fastq.so, and select_STR_reads.cpython-35m-x86_64-linux-gnu.so to select_STR_reads.so), but then the correct files were created in the bin folder (after "make install").

./merge_STR_reads and ./extend_STR_reads both print the usage options; however, 

./select_STR_reads leads to the following error:

  File "./select_STR_reads", line 75
    except GetoptError, err:
                      ^
SyntaxError: invalid syntax

python2 select_STR_reads leads to the following error:

Traceback (most recent call last):
  File "select_STR_reads", line 61, in <module>
    from select_STR_reads import *
ImportError: /home/user/workspace/SNP_caller/tools/BaitSTR/bin/select_STR_reads.so: undefined symbol: _Py_FalseStruct

python3 select_STR_reads leads to the following error:

  File "select_STR_reads", line 75
    except GetoptError, err:
                      ^
SyntaxError: invalid syntax

Any thoughts on how I can get this to run?

Thank you!!

**Comment by aakrosh** [comment]
The first issue (names of the .so files) is a consequence of  [PEP 3149](https://www.python.org/dev/peps/pep-3149/), which has been implemented since Python 3.2. So I believe what is happening is that 'make' is using python3 to create the .so files. BaitSTR does not support python3, so when you use 'python3' to run select_STR_reads it fails due to syntax issues. 'python2' fails as the *.so files have been compiled using python3.

You could try the following:
```
make clean
``` 
Replace 'python' with 'python2' in 'src/Makefile'. Then try 'make' again.  

Thanks.

**Comment by michaeldonaldson** [comment]
Hi Aakrosh, 

1. make clean 
2. replaced 'python' with 'python2' in 'src/Makefile'
3. make && make install
4. python2 select_STR_reads > prints the usage options :)

Thank you!

**Comment by aakrosh** [comment]
Great, glad that this was resolved. Thanks for your interest in BaitSTR.
